name: C# Quality Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["7.0", "8.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run StyleCop
        run: dotnet format --verify-no-changes

      - name: Run tests with coverage
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.opencover.xml
          fail_ci_if_error: true

      - name: Check coverage threshold
        run: dotnet test /p:CollectCoverage=true /p:Threshold=90 /p:ThresholdType=line

  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build release
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build
