"""Pluggable agent-context rendering for generated projects (#387).

``green init`` historically scaffolded agent context for exactly one
coding assistant: Claude Code (``CLAUDE.md`` + ``.claude/``). This
module makes the *format* pluggable while keeping the *content* single-
sourced (DRY): the canonical prose lives in ``reference/claude/docs/``
and the reference subagent profiles, and per-target serializers render
that shared content into each assistant's expected files.

Targets:

- ``claude`` (default): the existing ``CLAUDE.md`` + ``.claude/`` tree,
  emitted by :class:`~start_green_stay_green.generators.claude_md.\
ClaudeMdGenerator` and :class:`~start_green_stay_green.generators.\
subagents.SubagentsGenerator`. This module deliberately has no emitter
  for it so the default output stays byte-for-byte unchanged.
- ``agents-md``: a single ``AGENTS.md`` at the repository root,
  following the open agent-context convention consumed by many coding
  agents. The six split docs are folded in as sections and the subagent
  role descriptions become a roles table.
- ``aider``: ``CONVENTIONS.md`` plus a ``.aider.conf.yml`` that loads
  it into every aider chat (``read: CONVENTIONS.md``).

Rendering is fully deterministic — token substitution over static
reference files, no timestamps, no AI calls — so re-running ``green
init --agent ...`` is reproducible and safe (additive writes go through
the conflict-aware ``FileWriter``).
"""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Any
from typing import TYPE_CHECKING

import yaml

from start_green_stay_green.generators.claude_md import CLAUDE_DOC_NAMES
from start_green_stay_green.generators.claude_md import ClaudeMdGenerator
from start_green_stay_green.generators.subagents import REFERENCE_AGENTS_DIR
from start_green_stay_green.generators.subagents import REQUIRED_AGENTS
from start_green_stay_green.generators.subagents import split_frontmatter

if TYPE_CHECKING:
    from pathlib import Path

#: Target identifier for the existing Claude Code output (the default).
TARGET_CLAUDE = "claude"

#: Target identifier for the single-file AGENTS.md convention.
TARGET_AGENTS_MD = "agents-md"

#: Target identifier for aider (CONVENTIONS.md + .aider.conf.yml).
TARGET_AIDER = "aider"

#: Every supported agent-context target, in canonical (default-first)
#: order. The CLI validates ``--agent`` values against this tuple.
AGENT_CONTEXT_TARGETS: tuple[str, ...] = (
    TARGET_CLAUDE,
    TARGET_AGENTS_MD,
    TARGET_AIDER,
)

#: Filename emitted by the ``agents-md`` target.
AGENTS_MD_FILENAME = "AGENTS.md"

#: Conventions filename emitted by the ``aider`` target.
AIDER_CONVENTIONS_FILENAME = "CONVENTIONS.md"

#: Aider config filename emitted by the ``aider`` target.
AIDER_CONF_FILENAME = ".aider.conf.yml"

#: Prefix of the per-doc navigation chrome stripped when folding the
#: split docs into a single file (the links only make sense on disk).
_NAVIGATION_PREFIX = "**Navigation**:"

#: Links to sibling split docs, e.g. ``(quality-standards.md)`` or
#: ``(quality-standards.md#2-forbidden-patterns)``. Rewritten to
#: in-file anchors when the docs are folded into one file.
_DOC_LINK_PATTERN = re.compile(
    r"\((?:\./)?(?P<stem>"
    + "|".join(re.escape(name) for name in CLAUDE_DOC_NAMES)
    + r")\.md(?P<frag>#[^)]+)?\)"
)

_AGENTS_MD_INTRO = (
    "> Generated by Start Green Stay Green. This file follows the\n"
    "> AGENTS.md open agent-context convention: a single Markdown file\n"
    "> at the repository root that coding agents read for project\n"
    "> context. Every section below is rendered from the same canonical\n"
    "> content as the other generated agent-context formats.\n"
)

_AGENT_ROLES_INTRO = (
    "Specialist roles for structuring AI-assisted work on this project.\n"
    "When the `claude` context target is also generated, each role ships\n"
    "as a Claude Code subagent profile under `.claude/agents/`.\n"
)

_AIDER_INTRO = (
    "> Generated by Start Green Stay Green for AI pair-programming\n"
    "> assistants. Aider loads this file into every chat via the\n"
    "> generated `.aider.conf.yml` (`read: CONVENTIONS.md`). Every\n"
    "> section below is rendered from the same canonical content as\n"
    "> the other generated agent-context formats.\n"
)

_AIDER_CONF_CONTENT = (
    "# Generated by Start Green Stay Green.\n"
    "# Loads the shared project conventions into every aider chat.\n"
    "# Reference: https://aider.chat/docs/usage/conventions.html\n"
    f"read: {AIDER_CONVENTIONS_FILENAME}\n"
)


@dataclass(frozen=True)
class DocSection:
    """One canonical documentation section of the shared agent context.

    Attributes:
        stem: Doc stem from :data:`CLAUDE_DOC_NAMES` (e.g.
            ``"principles"``).
        title: The doc's H1 title text (without the ``# `` marker).
        body: Rendered doc content after the H1 line, tokens already
            substituted. Kept verbatim — serializers apply their own
            structural transforms (navigation stripping, link rewrites).
    """

    stem: str
    title: str
    body: str


@dataclass(frozen=True)
class AgentRole:
    """One specialist role sourced from a reference subagent profile.

    Attributes:
        name: Logical agent name (a :data:`REQUIRED_AGENTS` key, e.g.
            ``"quality-reviewer"``).
        description: The ``description`` field of the agent's YAML
            frontmatter.
    """

    name: str
    description: str


@dataclass(frozen=True)
class AgentContextContent:
    """The shared (target-independent) agent-context content.

    Authored once — loaded from the canonical reference files — and
    rendered per target by the serializers in this module.

    Attributes:
        project_name: Target project name.
        language: Primary project language.
        sections: Canonical doc sections in :data:`CLAUDE_DOC_NAMES`
            order.
        roles: Specialist roles in :data:`REQUIRED_AGENTS` declaration
            order.
    """

    project_name: str
    language: str
    sections: tuple[DocSection, ...]
    roles: tuple[AgentRole, ...]


def _parse_section(stem: str, rendered: str) -> DocSection:
    """Split a rendered reference doc into its H1 title and body.

    Args:
        stem: Doc stem (for error messages).
        rendered: Full rendered doc content.

    Returns:
        The parsed :class:`DocSection`.

    Raises:
        ValueError: If the doc does not start with an H1 title.
    """
    first_line, _, body = rendered.partition("\n")
    if not first_line.startswith("# "):
        msg = f"Reference doc '{stem}.md' must start with an H1 title"
        raise ValueError(msg)
    return DocSection(stem=stem, title=first_line[2:].strip(), body=body)


def _load_role(agent_name: str, agent_path: Path) -> AgentRole:
    """Read one reference agent's frontmatter into an :class:`AgentRole`.

    Args:
        agent_name: Logical agent name (the emitted role name).
        agent_path: Path to the reference agent source file.

    Returns:
        The parsed role.

    Raises:
        FileNotFoundError: If the reference agent file is missing.
        ValueError: If the frontmatter is malformed or has no
            ``description`` field.
    """
    if not agent_path.is_file():
        msg = f"Reference subagent not found: {agent_path}"
        raise FileNotFoundError(msg)
    frontmatter, _body = split_frontmatter(agent_path.read_text(encoding="utf-8"))
    yaml_text = frontmatter.strip().removeprefix("---").removesuffix("---")
    data = yaml.safe_load(yaml_text)
    description = data.get("description") if isinstance(data, dict) else None
    if not isinstance(description, str) or not description.strip():
        msg = (
            f"Reference subagent '{agent_name}' frontmatter is missing a "
            f"'description' field: {agent_path}"
        )
        raise ValueError(msg)
    return AgentRole(name=agent_name, description=description.strip())


def load_agent_context_content(
    project_config: dict[str, Any],
    *,
    reference_dir: Path | None = None,
    agents_dir: Path | None = None,
) -> AgentContextContent:
    """Load the shared agent-context content from the reference tree.

    The doc sections are rendered through
    :meth:`ClaudeMdGenerator.render_docs` (the same deterministic token
    substitution the Claude target uses), so every target serializes
    the exact same canonical content.

    Args:
        project_config: Project configuration with keys
            ``project_name``, ``language``, ``scripts``, ``skills``.
        reference_dir: Override for the ``reference/claude`` directory
            (used by tests). Defaults to the packaged reference tree.
        agents_dir: Override for the reference agents directory.
            Defaults to :data:`REFERENCE_AGENTS_DIR`.

    Returns:
        The loaded :class:`AgentContextContent`.

    Raises:
        ValueError: If reference docs or agent frontmatter are invalid.
        FileNotFoundError: If a required reference file is missing.
    """
    generator = ClaudeMdGenerator(reference_dir=reference_dir)
    docs = generator.render_docs(project_config)
    sections = tuple(_parse_section(stem, docs[stem]) for stem in CLAUDE_DOC_NAMES)

    resolved_agents_dir = agents_dir if agents_dir is not None else REFERENCE_AGENTS_DIR
    roles = tuple(
        _load_role(agent_name, resolved_agents_dir / source_file)
        for agent_name, source_file in REQUIRED_AGENTS.items()
    )

    return AgentContextContent(
        project_name=str(project_config.get("project_name", "your-project")),
        language=str(project_config.get("language", "python")),
        sections=sections,
        roles=roles,
    )


def _slugify(title: str) -> str:
    """Convert a section title to its GitHub-style heading anchor.

    Args:
        title: Heading text (e.g. ``"Tool Usage & Code Standards"``).

    Returns:
        The anchor fragment (e.g. ``"tool-usage--code-standards"``).
    """
    cleaned = re.sub(r"[^a-z0-9 -]", "", title.lower())
    return cleaned.replace(" ", "-")


def _strip_navigation_lines(body: str) -> str:
    """Remove the per-doc navigation chrome from a folded doc body.

    The ``**Navigation**: …`` lines link between the on-disk split docs
    and back to ``CLAUDE.md``; folded into a single file they would be
    broken links. The blank line immediately following each navigation
    line is dropped with it so no double-blank gaps are left behind.

    Args:
        body: Doc body content.

    Returns:
        The body without navigation lines.
    """
    kept: list[str] = []
    skip_next_blank = False
    for line in body.split("\n"):
        if line.startswith(_NAVIGATION_PREFIX):
            skip_next_blank = True
            continue
        if skip_next_blank and not line.strip():
            skip_next_blank = False
            continue
        skip_next_blank = False
        kept.append(line)
    return "\n".join(kept)


def _rewrite_internal_links(body: str, anchors: dict[str, str]) -> str:
    """Rewrite sibling-doc links to in-file anchors for a folded file.

    ``(quality-standards.md)`` becomes ``(#quality-standards)`` (the
    folded section's heading anchor) and
    ``(quality-standards.md#frag)`` becomes ``(#frag)``.

    Args:
        body: Doc body content.
        anchors: Mapping of doc stem to its folded heading anchor.

    Returns:
        The body with intra-tree links rewritten.
    """

    def _substitute(match: re.Match[str]) -> str:
        fragment = match.group("frag")
        if fragment:
            return f"({fragment})"
        return f"(#{anchors[match.group('stem')]})"

    return _DOC_LINK_PATTERN.sub(_substitute, body)


def _fold_sections(sections: tuple[DocSection, ...]) -> str:
    """Fold the canonical doc sections into one markdown document body.

    Each section becomes an H2 heading followed by its body, with the
    on-disk navigation chrome stripped and sibling-doc links rewritten
    to in-file anchors.

    Args:
        sections: Canonical doc sections.

    Returns:
        The folded markdown, LF line endings, trailing newline included.
    """
    anchors = {section.stem: _slugify(section.title) for section in sections}
    parts: list[str] = []
    for section in sections:
        body = _strip_navigation_lines(section.body)
        body = _rewrite_internal_links(body, anchors)
        parts.append(f"## {section.title}\n\n{body.strip()}\n")
    return "\n".join(parts)


def _table_cell(text: str) -> str:
    """Make free text safe for a one-line markdown table cell.

    Args:
        text: Cell text (may contain newlines or pipes).

    Returns:
        Whitespace-collapsed text with pipes escaped.
    """
    return " ".join(text.split()).replace("|", "\\|")


def render_agents_md(content: AgentContextContent) -> str:
    """Render the shared content as a single ``AGENTS.md`` file.

    Args:
        content: The shared agent-context content.

    Returns:
        Deterministic markdown content using LF line endings only.
    """
    rows = "\n".join(
        f"| `{role.name}` | {_table_cell(role.description)} |" for role in content.roles
    )
    return (
        f"# {content.project_name} — Agent Context\n"
        "\n"
        f"**Primary language**: {content.language}\n"
        "\n"
        f"{_AGENTS_MD_INTRO}"
        "\n"
        "---\n"
        "\n"
        "## Agent Roles\n"
        "\n"
        f"{_AGENT_ROLES_INTRO}"
        "\n"
        "| Role | Focus |\n"
        "| --- | --- |\n"
        f"{rows}\n"
        "\n"
        "---\n"
        "\n"
        f"{_fold_sections(content.sections)}"
    )


def render_aider_conventions(content: AgentContextContent) -> str:
    """Render the shared content as an aider ``CONVENTIONS.md`` file.

    Args:
        content: The shared agent-context content.

    Returns:
        Deterministic markdown content using LF line endings only.
    """
    return (
        f"# {content.project_name} — Coding Conventions\n"
        "\n"
        f"**Primary language**: {content.language}\n"
        "\n"
        f"{_AIDER_INTRO}"
        "\n"
        "---\n"
        "\n"
        f"{_fold_sections(content.sections)}"
    )


def render_aider_conf() -> str:
    """Render the ``.aider.conf.yml`` that loads the conventions file.

    Returns:
        Deterministic YAML content with a single ``read`` entry.
    """
    return _AIDER_CONF_CONTENT


def render_target_files(
    target: str,
    content: AgentContextContent,
) -> dict[str, str]:
    """Render every file the given non-Claude target emits.

    Args:
        target: One of :data:`TARGET_AGENTS_MD` or :data:`TARGET_AIDER`.
        content: The shared agent-context content.

    Returns:
        Mapping of project-root-relative filename to file content.

    Raises:
        ValueError: For unknown targets, and for ``claude`` — the
            Claude output is emitted by the existing ``ClaudeMd`` and
            ``Subagents`` generators, never by this module, so the
            default output stays byte-for-byte unchanged.
    """
    if target == TARGET_AGENTS_MD:
        return {AGENTS_MD_FILENAME: render_agents_md(content)}
    if target == TARGET_AIDER:
        return {
            AIDER_CONVENTIONS_FILENAME: render_aider_conventions(content),
            AIDER_CONF_FILENAME: render_aider_conf(),
        }
    msg = (
        f"No standalone agent-context emitter for target {target!r}. "
        f"Emitter targets: {TARGET_AGENTS_MD}, {TARGET_AIDER} "
        f"('{TARGET_CLAUDE}' is emitted by the ClaudeMd/Subagents generators)."
    )
    raise ValueError(msg)
