"""Ralph fleet-loop generator for target projects.

Copies the opt-in "Ralph loop" scaffolding (autonomous fleet orchestrator,
subagent taxonomy, worktree fleet scripts, and maintenance-scan GitHub
Actions) from ``reference/ralph/`` into a generated project. Unlike skills
and subagents, this content is never generated by default — it assumes a
GitHub-hosted issue/PR backlog, git worktrees, and manual secret/label
setup after generation (see the generated ``FLEET.md`` and ``PROMPT.md``).

The two skills the bundle requires (``scan-issue-writer``, ``de-slopify``)
live in ``reference/skills/`` alongside every other skill, not under
``reference/ralph/`` — copying from there avoids duplicating their content
in two reference trees.
"""

from __future__ import annotations

from pathlib import Path
import shutil
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from start_green_stay_green.utils.file_writer import FileWriter

# Reference source directories
REFERENCE_RALPH_DIR = Path(__file__).parent.parent.parent / "reference" / "ralph"
REFERENCE_SKILLS_DIR = Path(__file__).parent.parent.parent / "reference" / "skills"

# Skills the ralph-loop bundle requires, sourced from the shared skills tree.
# discord-ralph-recap is a standalone skill (not part of any bundle upstream)
# but is included here so --with-ralph-loop gives a generated project the
# complete SGSG-parity experience in one flag; its workflow
# (reference/ralph/github/workflows/ralph-recap.yml) needs no separate wiring
# since RALPH_LOOP_TREES already copies that whole directory.
RALPH_LOOP_SKILLS = ["scan-issue-writer", "de-slopify", "discord-ralph-recap"]

# (reference subtree, target-relative subtree) tree-copy pairs.
RALPH_LOOP_TREES: tuple[tuple[str, str], ...] = (
    ("agents", ".claude/agents"),
    ("commands", ".claude/commands"),
    ("scripts", "scripts/ralph"),
    ("github/workflows", ".github/workflows"),
    ("prompts", "prompts"),
)

# (reference file, target-relative file) single-file copy pairs.
RALPH_LOOP_FILES: tuple[tuple[str, str], ...] = (
    ("github/deslop-areas.json", ".github/deslop-areas.json"),
)


def _copy_dir(
    source_dir: Path,
    target_dir: Path,
    file_writer: FileWriter | None,
) -> None:
    """Copy one directory tree, via ``file_writer`` when given."""
    if file_writer is not None:
        file_writer.copy_tree(source_dir, target_dir)
        return
    target_dir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source_dir, target_dir, dirs_exist_ok=True)


def _copy_ralph_trees(target_dir: Path, file_writer: FileWriter | None) -> None:
    """Copy each ``RALPH_LOOP_TREES`` directory into ``target_dir``."""
    for subtree, target_subtree in RALPH_LOOP_TREES:
        source_dir = REFERENCE_RALPH_DIR / subtree
        if not source_dir.is_dir():
            msg = f"Reference ralph tree not found: {subtree}"
            raise FileNotFoundError(msg)
        _copy_dir(source_dir, target_dir / target_subtree, file_writer)


def _copy_ralph_files(target_dir: Path, file_writer: FileWriter | None) -> None:
    """Copy each ``RALPH_LOOP_FILES`` single file into ``target_dir``."""
    for source_rel, target_rel in RALPH_LOOP_FILES:
        source_file = REFERENCE_RALPH_DIR / source_rel
        if not source_file.is_file():
            msg = f"Reference ralph file not found: {source_rel}"
            raise FileNotFoundError(msg)
        target_file = target_dir / target_rel
        content = source_file.read_text(encoding="utf-8")
        if file_writer is not None:
            file_writer.write_file(target_file, content)
        else:
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")


def _copy_ralph_skills(target_dir: Path, file_writer: FileWriter | None) -> None:
    """Copy each ``RALPH_LOOP_SKILLS`` directory from the shared skills tree."""
    skills_target = target_dir / ".claude" / "skills"
    for skill_name in RALPH_LOOP_SKILLS:
        source_dir = REFERENCE_SKILLS_DIR / skill_name
        if not source_dir.is_dir():
            msg = f"Reference skill not found: {skill_name}"
            raise FileNotFoundError(msg)
        _copy_dir(source_dir, skills_target / skill_name, file_writer)


def copy_ralph_loop(
    target_dir: Path,
    file_writer: FileWriter | None = None,
) -> None:
    """Copy the Ralph fleet-loop scaffolding into ``target_dir``.

    Args:
        target_dir: Root of the generated project.
        file_writer: Optional FileWriter for additive behavior (handles
            --force / --interactive conflict resolution). When ``None``,
            copies directly with ``shutil``/``Path.write_text``.

    Raises:
        FileNotFoundError: If a required reference tree or file is missing.
    """
    _copy_ralph_trees(target_dir, file_writer)
    _copy_ralph_files(target_dir, file_writer)
    _copy_ralph_skills(target_dir, file_writer)
